/**
 * @fileoverview gRPC-Web generated client stub for account
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.19.1
// source: account.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.account = require('./account_pb.cjs');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.account.AccountServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.account.AccountServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.account.Empty,
 *   !proto.account.AccountListResponse>}
 */
const methodDescriptor_AccountService_ListAccounts = new grpc.web.MethodDescriptor(
  '/account.AccountService/ListAccounts',
  grpc.web.MethodType.UNARY,
  proto.account.Empty,
  proto.account.AccountListResponse,
  /**
   * @param {!proto.account.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.account.AccountListResponse.deserializeBinary
);


/**
 * @param {!proto.account.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.account.AccountListResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.account.AccountListResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.account.AccountServiceClient.prototype.listAccounts =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/account.AccountService/ListAccounts',
      request,
      metadata || {},
      methodDescriptor_AccountService_ListAccounts,
      callback);
};


/**
 * @param {!proto.account.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.account.AccountListResponse>}
 *     Promise that resolves to the response
 */
proto.account.AccountServicePromiseClient.prototype.listAccounts =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/account.AccountService/ListAccounts',
      request,
      metadata || {},
      methodDescriptor_AccountService_ListAccounts);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.account.CreateAccountRequest,
 *   !proto.account.AccountResponse>}
 */
const methodDescriptor_AccountService_CreateAccount = new grpc.web.MethodDescriptor(
  '/account.AccountService/CreateAccount',
  grpc.web.MethodType.UNARY,
  proto.account.CreateAccountRequest,
  proto.account.AccountResponse,
  /**
   * @param {!proto.account.CreateAccountRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.account.AccountResponse.deserializeBinary
);


/**
 * @param {!proto.account.CreateAccountRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.account.AccountResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.account.AccountResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.account.AccountServiceClient.prototype.createAccount =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/account.AccountService/CreateAccount',
      request,
      metadata || {},
      methodDescriptor_AccountService_CreateAccount,
      callback);
};


/**
 * @param {!proto.account.CreateAccountRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.account.AccountResponse>}
 *     Promise that resolves to the response
 */
proto.account.AccountServicePromiseClient.prototype.createAccount =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/account.AccountService/CreateAccount',
      request,
      metadata || {},
      methodDescriptor_AccountService_CreateAccount);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.account.GetAccountRequest,
 *   !proto.account.AccountResponse>}
 */
const methodDescriptor_AccountService_GetAccount = new grpc.web.MethodDescriptor(
  '/account.AccountService/GetAccount',
  grpc.web.MethodType.UNARY,
  proto.account.GetAccountRequest,
  proto.account.AccountResponse,
  /**
   * @param {!proto.account.GetAccountRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.account.AccountResponse.deserializeBinary
);


/**
 * @param {!proto.account.GetAccountRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.account.AccountResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.account.AccountResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.account.AccountServiceClient.prototype.getAccount =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/account.AccountService/GetAccount',
      request,
      metadata || {},
      methodDescriptor_AccountService_GetAccount,
      callback);
};


/**
 * @param {!proto.account.GetAccountRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.account.AccountResponse>}
 *     Promise that resolves to the response
 */
proto.account.AccountServicePromiseClient.prototype.getAccount =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/account.AccountService/GetAccount',
      request,
      metadata || {},
      methodDescriptor_AccountService_GetAccount);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.account.DeleteAccountRequest,
 *   !proto.account.DeleteAccountResponse>}
 */
const methodDescriptor_AccountService_DeleteAccount = new grpc.web.MethodDescriptor(
  '/account.AccountService/DeleteAccount',
  grpc.web.MethodType.UNARY,
  proto.account.DeleteAccountRequest,
  proto.account.DeleteAccountResponse,
  /**
   * @param {!proto.account.DeleteAccountRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.account.DeleteAccountResponse.deserializeBinary
);


/**
 * @param {!proto.account.DeleteAccountRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.account.DeleteAccountResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.account.DeleteAccountResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.account.AccountServiceClient.prototype.deleteAccount =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/account.AccountService/DeleteAccount',
      request,
      metadata || {},
      methodDescriptor_AccountService_DeleteAccount,
      callback);
};


/**
 * @param {!proto.account.DeleteAccountRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.account.DeleteAccountResponse>}
 *     Promise that resolves to the response
 */
proto.account.AccountServicePromiseClient.prototype.deleteAccount =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/account.AccountService/DeleteAccount',
      request,
      metadata || {},
      methodDescriptor_AccountService_DeleteAccount);
};


module.exports = proto.account;

