/**
 * @fileoverview gRPC-Web generated client stub for market
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.19.1
// source: market.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.market = require('./market_pb.cjs');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.market.MarketDataServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.market.MarketDataServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.market.EmptyRequest,
 *   !proto.market.SymbolListResponse>}
 */
const methodDescriptor_MarketDataService_GetActiveSymbols = new grpc.web.MethodDescriptor(
  '/market.MarketDataService/GetActiveSymbols',
  grpc.web.MethodType.UNARY,
  proto.market.EmptyRequest,
  proto.market.SymbolListResponse,
  /**
   * @param {!proto.market.EmptyRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.market.SymbolListResponse.deserializeBinary
);


/**
 * @param {!proto.market.EmptyRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.market.SymbolListResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.market.SymbolListResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.market.MarketDataServiceClient.prototype.getActiveSymbols =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/market.MarketDataService/GetActiveSymbols',
      request,
      metadata || {},
      methodDescriptor_MarketDataService_GetActiveSymbols,
      callback);
};


/**
 * @param {!proto.market.EmptyRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.market.SymbolListResponse>}
 *     Promise that resolves to the response
 */
proto.market.MarketDataServicePromiseClient.prototype.getActiveSymbols =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/market.MarketDataService/GetActiveSymbols',
      request,
      metadata || {},
      methodDescriptor_MarketDataService_GetActiveSymbols);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.market.GetSymbolRequest,
 *   !proto.market.SymbolResponse>}
 */
const methodDescriptor_MarketDataService_GetSymbol = new grpc.web.MethodDescriptor(
  '/market.MarketDataService/GetSymbol',
  grpc.web.MethodType.UNARY,
  proto.market.GetSymbolRequest,
  proto.market.SymbolResponse,
  /**
   * @param {!proto.market.GetSymbolRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.market.SymbolResponse.deserializeBinary
);


/**
 * @param {!proto.market.GetSymbolRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.market.SymbolResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.market.SymbolResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.market.MarketDataServiceClient.prototype.getSymbol =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/market.MarketDataService/GetSymbol',
      request,
      metadata || {},
      methodDescriptor_MarketDataService_GetSymbol,
      callback);
};


/**
 * @param {!proto.market.GetSymbolRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.market.SymbolResponse>}
 *     Promise that resolves to the response
 */
proto.market.MarketDataServicePromiseClient.prototype.getSymbol =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/market.MarketDataService/GetSymbol',
      request,
      metadata || {},
      methodDescriptor_MarketDataService_GetSymbol);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.market.AddSymbolRequest,
 *   !proto.market.SymbolResponse>}
 */
const methodDescriptor_MarketDataService_AddSymbol = new grpc.web.MethodDescriptor(
  '/market.MarketDataService/AddSymbol',
  grpc.web.MethodType.UNARY,
  proto.market.AddSymbolRequest,
  proto.market.SymbolResponse,
  /**
   * @param {!proto.market.AddSymbolRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.market.SymbolResponse.deserializeBinary
);


/**
 * @param {!proto.market.AddSymbolRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.market.SymbolResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.market.SymbolResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.market.MarketDataServiceClient.prototype.addSymbol =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/market.MarketDataService/AddSymbol',
      request,
      metadata || {},
      methodDescriptor_MarketDataService_AddSymbol,
      callback);
};


/**
 * @param {!proto.market.AddSymbolRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.market.SymbolResponse>}
 *     Promise that resolves to the response
 */
proto.market.MarketDataServicePromiseClient.prototype.addSymbol =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/market.MarketDataService/AddSymbol',
      request,
      metadata || {},
      methodDescriptor_MarketDataService_AddSymbol);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.market.DeleteSymbolRequest,
 *   !proto.market.DeleteSymbolResponse>}
 */
const methodDescriptor_MarketDataService_DeleteSymbol = new grpc.web.MethodDescriptor(
  '/market.MarketDataService/DeleteSymbol',
  grpc.web.MethodType.UNARY,
  proto.market.DeleteSymbolRequest,
  proto.market.DeleteSymbolResponse,
  /**
   * @param {!proto.market.DeleteSymbolRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.market.DeleteSymbolResponse.deserializeBinary
);


/**
 * @param {!proto.market.DeleteSymbolRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.market.DeleteSymbolResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.market.DeleteSymbolResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.market.MarketDataServiceClient.prototype.deleteSymbol =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/market.MarketDataService/DeleteSymbol',
      request,
      metadata || {},
      methodDescriptor_MarketDataService_DeleteSymbol,
      callback);
};


/**
 * @param {!proto.market.DeleteSymbolRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.market.DeleteSymbolResponse>}
 *     Promise that resolves to the response
 */
proto.market.MarketDataServicePromiseClient.prototype.deleteSymbol =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/market.MarketDataService/DeleteSymbol',
      request,
      metadata || {},
      methodDescriptor_MarketDataService_DeleteSymbol);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.market.GetRecentTradesRequest,
 *   !proto.market.RecentTradesResponse>}
 */
const methodDescriptor_MarketDataService_GetRecentTrades = new grpc.web.MethodDescriptor(
  '/market.MarketDataService/GetRecentTrades',
  grpc.web.MethodType.UNARY,
  proto.market.GetRecentTradesRequest,
  proto.market.RecentTradesResponse,
  /**
   * @param {!proto.market.GetRecentTradesRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.market.RecentTradesResponse.deserializeBinary
);


/**
 * @param {!proto.market.GetRecentTradesRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.market.RecentTradesResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.market.RecentTradesResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.market.MarketDataServiceClient.prototype.getRecentTrades =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/market.MarketDataService/GetRecentTrades',
      request,
      metadata || {},
      methodDescriptor_MarketDataService_GetRecentTrades,
      callback);
};


/**
 * @param {!proto.market.GetRecentTradesRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.market.RecentTradesResponse>}
 *     Promise that resolves to the response
 */
proto.market.MarketDataServicePromiseClient.prototype.getRecentTrades =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/market.MarketDataService/GetRecentTrades',
      request,
      metadata || {},
      methodDescriptor_MarketDataService_GetRecentTrades);
};


module.exports = proto.market;

