/**
 * @fileoverview gRPC-Web generated client stub for matching
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.19.1
// source: matching.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.matching = require('./matching_pb.cjs');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.matching.MatchingServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.matching.MatchingServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.matching.GetOrderBookRequest,
 *   !proto.matching.OrderBookResponse>}
 */
const methodDescriptor_MatchingService_GetOrderBookSnapshot = new grpc.web.MethodDescriptor(
  '/matching.MatchingService/GetOrderBookSnapshot',
  grpc.web.MethodType.UNARY,
  proto.matching.GetOrderBookRequest,
  proto.matching.OrderBookResponse,
  /**
   * @param {!proto.matching.GetOrderBookRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.matching.OrderBookResponse.deserializeBinary
);


/**
 * @param {!proto.matching.GetOrderBookRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.matching.OrderBookResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.matching.OrderBookResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.matching.MatchingServiceClient.prototype.getOrderBookSnapshot =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/matching.MatchingService/GetOrderBookSnapshot',
      request,
      metadata || {},
      methodDescriptor_MatchingService_GetOrderBookSnapshot,
      callback);
};


/**
 * @param {!proto.matching.GetOrderBookRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.matching.OrderBookResponse>}
 *     Promise that resolves to the response
 */
proto.matching.MatchingServicePromiseClient.prototype.getOrderBookSnapshot =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/matching.MatchingService/GetOrderBookSnapshot',
      request,
      metadata || {},
      methodDescriptor_MatchingService_GetOrderBookSnapshot);
};


module.exports = proto.matching;

