/**
 * @fileoverview gRPC-Web generated client stub for order
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.19.1
// source: order.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.order = require('./order_pb.cjs');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.order.OrderManagementServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.order.OrderManagementServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.order.PlaceOrderRequest,
 *   !proto.order.OrderResponse>}
 */
const methodDescriptor_OrderManagementService_PlaceOrder = new grpc.web.MethodDescriptor(
  '/order.OrderManagementService/PlaceOrder',
  grpc.web.MethodType.UNARY,
  proto.order.PlaceOrderRequest,
  proto.order.OrderResponse,
  /**
   * @param {!proto.order.PlaceOrderRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.order.OrderResponse.deserializeBinary
);


/**
 * @param {!proto.order.PlaceOrderRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.order.OrderResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.order.OrderResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.order.OrderManagementServiceClient.prototype.placeOrder =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/order.OrderManagementService/PlaceOrder',
      request,
      metadata || {},
      methodDescriptor_OrderManagementService_PlaceOrder,
      callback);
};


/**
 * @param {!proto.order.PlaceOrderRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.order.OrderResponse>}
 *     Promise that resolves to the response
 */
proto.order.OrderManagementServicePromiseClient.prototype.placeOrder =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/order.OrderManagementService/PlaceOrder',
      request,
      metadata || {},
      methodDescriptor_OrderManagementService_PlaceOrder);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.order.ModifyOrderRequest,
 *   !proto.order.OrderResponse>}
 */
const methodDescriptor_OrderManagementService_ModifyOrder = new grpc.web.MethodDescriptor(
  '/order.OrderManagementService/ModifyOrder',
  grpc.web.MethodType.UNARY,
  proto.order.ModifyOrderRequest,
  proto.order.OrderResponse,
  /**
   * @param {!proto.order.ModifyOrderRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.order.OrderResponse.deserializeBinary
);


/**
 * @param {!proto.order.ModifyOrderRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.order.OrderResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.order.OrderResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.order.OrderManagementServiceClient.prototype.modifyOrder =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/order.OrderManagementService/ModifyOrder',
      request,
      metadata || {},
      methodDescriptor_OrderManagementService_ModifyOrder,
      callback);
};


/**
 * @param {!proto.order.ModifyOrderRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.order.OrderResponse>}
 *     Promise that resolves to the response
 */
proto.order.OrderManagementServicePromiseClient.prototype.modifyOrder =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/order.OrderManagementService/ModifyOrder',
      request,
      metadata || {},
      methodDescriptor_OrderManagementService_ModifyOrder);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.order.CancelOrderRequest,
 *   !proto.order.CancelOrderResponse>}
 */
const methodDescriptor_OrderManagementService_CancelOrder = new grpc.web.MethodDescriptor(
  '/order.OrderManagementService/CancelOrder',
  grpc.web.MethodType.UNARY,
  proto.order.CancelOrderRequest,
  proto.order.CancelOrderResponse,
  /**
   * @param {!proto.order.CancelOrderRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.order.CancelOrderResponse.deserializeBinary
);


/**
 * @param {!proto.order.CancelOrderRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.order.CancelOrderResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.order.CancelOrderResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.order.OrderManagementServiceClient.prototype.cancelOrder =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/order.OrderManagementService/CancelOrder',
      request,
      metadata || {},
      methodDescriptor_OrderManagementService_CancelOrder,
      callback);
};


/**
 * @param {!proto.order.CancelOrderRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.order.CancelOrderResponse>}
 *     Promise that resolves to the response
 */
proto.order.OrderManagementServicePromiseClient.prototype.cancelOrder =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/order.OrderManagementService/CancelOrder',
      request,
      metadata || {},
      methodDescriptor_OrderManagementService_CancelOrder);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.order.GetOpenOrdersRequest,
 *   !proto.order.OrderListResponse>}
 */
const methodDescriptor_OrderManagementService_GetOpenOrders = new grpc.web.MethodDescriptor(
  '/order.OrderManagementService/GetOpenOrders',
  grpc.web.MethodType.UNARY,
  proto.order.GetOpenOrdersRequest,
  proto.order.OrderListResponse,
  /**
   * @param {!proto.order.GetOpenOrdersRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.order.OrderListResponse.deserializeBinary
);


/**
 * @param {!proto.order.GetOpenOrdersRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.order.OrderListResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.order.OrderListResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.order.OrderManagementServiceClient.prototype.getOpenOrders =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/order.OrderManagementService/GetOpenOrders',
      request,
      metadata || {},
      methodDescriptor_OrderManagementService_GetOpenOrders,
      callback);
};


/**
 * @param {!proto.order.GetOpenOrdersRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.order.OrderListResponse>}
 *     Promise that resolves to the response
 */
proto.order.OrderManagementServicePromiseClient.prototype.getOpenOrders =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/order.OrderManagementService/GetOpenOrders',
      request,
      metadata || {},
      methodDescriptor_OrderManagementService_GetOpenOrders);
};


module.exports = proto.order;

