/**
 * @fileoverview gRPC-Web generated client stub for portfolio
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.19.1
// source: portfolio.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.portfolio = require('./portfolio_pb.cjs');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.portfolio.PortfolioServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.portfolio.PortfolioServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.portfolio.GetBalancesRequest,
 *   !proto.portfolio.BalancesResponse>}
 */
const methodDescriptor_PortfolioService_GetBalances = new grpc.web.MethodDescriptor(
  '/portfolio.PortfolioService/GetBalances',
  grpc.web.MethodType.UNARY,
  proto.portfolio.GetBalancesRequest,
  proto.portfolio.BalancesResponse,
  /**
   * @param {!proto.portfolio.GetBalancesRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.portfolio.BalancesResponse.deserializeBinary
);


/**
 * @param {!proto.portfolio.GetBalancesRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.portfolio.BalancesResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.portfolio.BalancesResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.portfolio.PortfolioServiceClient.prototype.getBalances =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/portfolio.PortfolioService/GetBalances',
      request,
      metadata || {},
      methodDescriptor_PortfolioService_GetBalances,
      callback);
};


/**
 * @param {!proto.portfolio.GetBalancesRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.portfolio.BalancesResponse>}
 *     Promise that resolves to the response
 */
proto.portfolio.PortfolioServicePromiseClient.prototype.getBalances =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/portfolio.PortfolioService/GetBalances',
      request,
      metadata || {},
      methodDescriptor_PortfolioService_GetBalances);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.portfolio.GetTradeHistoryRequest,
 *   !proto.portfolio.TradeHistoryResponse>}
 */
const methodDescriptor_PortfolioService_GetTradeHistory = new grpc.web.MethodDescriptor(
  '/portfolio.PortfolioService/GetTradeHistory',
  grpc.web.MethodType.UNARY,
  proto.portfolio.GetTradeHistoryRequest,
  proto.portfolio.TradeHistoryResponse,
  /**
   * @param {!proto.portfolio.GetTradeHistoryRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.portfolio.TradeHistoryResponse.deserializeBinary
);


/**
 * @param {!proto.portfolio.GetTradeHistoryRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.portfolio.TradeHistoryResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.portfolio.TradeHistoryResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.portfolio.PortfolioServiceClient.prototype.getTradeHistory =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/portfolio.PortfolioService/GetTradeHistory',
      request,
      metadata || {},
      methodDescriptor_PortfolioService_GetTradeHistory,
      callback);
};


/**
 * @param {!proto.portfolio.GetTradeHistoryRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.portfolio.TradeHistoryResponse>}
 *     Promise that resolves to the response
 */
proto.portfolio.PortfolioServicePromiseClient.prototype.getTradeHistory =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/portfolio.PortfolioService/GetTradeHistory',
      request,
      metadata || {},
      methodDescriptor_PortfolioService_GetTradeHistory);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.portfolio.ModifyBalanceRequest,
 *   !proto.portfolio.ModifyBalanceResponse>}
 */
const methodDescriptor_PortfolioService_ModifyBalance = new grpc.web.MethodDescriptor(
  '/portfolio.PortfolioService/ModifyBalance',
  grpc.web.MethodType.UNARY,
  proto.portfolio.ModifyBalanceRequest,
  proto.portfolio.ModifyBalanceResponse,
  /**
   * @param {!proto.portfolio.ModifyBalanceRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.portfolio.ModifyBalanceResponse.deserializeBinary
);


/**
 * @param {!proto.portfolio.ModifyBalanceRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.portfolio.ModifyBalanceResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.portfolio.ModifyBalanceResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.portfolio.PortfolioServiceClient.prototype.modifyBalance =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/portfolio.PortfolioService/ModifyBalance',
      request,
      metadata || {},
      methodDescriptor_PortfolioService_ModifyBalance,
      callback);
};


/**
 * @param {!proto.portfolio.ModifyBalanceRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.portfolio.ModifyBalanceResponse>}
 *     Promise that resolves to the response
 */
proto.portfolio.PortfolioServicePromiseClient.prototype.modifyBalance =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/portfolio.PortfolioService/ModifyBalance',
      request,
      metadata || {},
      methodDescriptor_PortfolioService_ModifyBalance);
};


module.exports = proto.portfolio;

